#!/bin/bash

num=1
for run in {1..10}
do
	python divideAndConquer.py 100V$num
	((num += 1))
done

num=1
for run in {1..10}
do
	python divideAndConquer.py 1000V$num
	((num += 1))
done

num=1
for run in {1..10}
do
	python divideAndConquer.py 10000V$num
	((num += 1))
done

num=1
for run in {1..10}
do
	python divideAndConquer.py 100000V$num
	((num += 1))
done